language: python
python:
  - "3.7"

# command to install dependencies
install:
  - pip install .  
  - pip install coverage
  - pip install coveralls

# command to run tests
script:
  - coverage run -m unittest discover tests
  - coverage report

after_success:
    coveralls
